pub static FAMOUS_PEOPLE: [&'static str; 325] = [
    "Albert Einstein",
    "Isaac Newton",
    "Galileo Galilei",
    "Marie Curie",
    "Charles Darwin",
    "Nikola Tesla",
    "Leonardo da Vinci",
    "Stephen Hawking",
    "Aristotle",
    "Socrates",
    "Plato",
    "Alan Turing",
    "Ada Lovelace",
    "Carl Sagan",
    "Niels Bohr",
    "Richard Feynman",
    "Elon Musk",
    "Bill Gates",
    "Steve Jobs",
    "Mark Zuckerberg",
    "Jeff Bezos",
    "Larry Page",
    "Sergey Brin",
    "Sundar Pichai",
    "Satya Nadella",
    "Tim Cook",
    "Warren Buffett",
    "Oprah Winfrey",
    "Barack Obama",
    "Donald Trump",
    "Joe Biden",
    "George Washington",
    "Abraham Lincoln",
    "Franklin D. Roosevelt",
    "John F. Kennedy",
    "Theodore Roosevelt",
    "Ronald Reagan",
    "Mahatma Gandhi",
    "Nelson Mandela",
    "Winston Churchill",
    "Queen Elizabeth II",
    "Charles III",
    "Vladimir Putin",
    "Xi Jinping",
    "Angela Merkel",
    "Emmanuel Macron",
    "Justin Trudeau",
    "Narendra Modi",
    "Jacinda Ardern",
    "Volodymyr Zelenskyy",
    "Kobe Bryant",
    "LeBron James",
    "Michael Jordan",
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Roger Federer",
    "Serena Williams",
    "Usain Bolt",
    "Muhammad Ali",
    "Tiger Woods",
    "Tom Brady",
    "Michael Phelps",
    "Simone Biles",
    "Diego Maradona",
    "Neymar Jr.",
    "Billie Jean King",
    "Jackie Robinson",
    "Babe Ruth",
    "Pelé",
    "Larry Bird",
    "Stephen Curry",
    "Shaquille O’Neal",
    "Magic Johnson",
    "Kylian Mbappé",
    "Megan Rapinoe",
    "Taylor Swift",
    "Beyoncé",
    "Adele",
    "Lady Gaga",
    "Ed Sheeran",
    "Drake",
    "Rihanna",
    "Kanye West",
    "Eminem",
    "Bruno Mars",
    "Elvis Presley",
    "Michael Jackson",
    "Freddie Mercury",
    "Whitney Houston",
    "Bob Dylan",
    "Paul McCartney",
    "John Lennon",
    "George Harrison",
    "Ringo Starr",
    "David Bowie",
    "Prince",
    "Madonna",
    "Frank Sinatra",
    "Aretha Franklin",
    "Dolly Parton",
    "Billie Eilish",
    "The Weeknd",
    "Post Malone",
    "Harry Styles",
    "Olivia Rodrigo",
    "Timothée Chalamet",
    "Zendaya",
    "Tom Holland",
    "Robert Downey Jr.",
    "Scarlett Johansson",
    "Chris Evans",
    "Chris Hemsworth",
    "Mark Ruffalo",
    "Benedict Cumberbatch",
    "Samuel L. Jackson",
    "Dwayne Johnson",
    "Vin Diesel",
    "Jason Statham",
    "Keanu Reeves",
    "Tom Cruise",
    "Johnny Depp",
    "Leonardo DiCaprio",
    "Brad Pitt",
    "George Clooney",
    "Matt Damon",
    "Anne Hathaway",
    "Natalie Portman",
    "Jennifer Lawrence",
    "Meryl Streep",
    "Cate Blanchett",
    "Angelina Jolie",
    "Emma Stone",
    "Julia Roberts",
    "Sandra Bullock",
    "Charlize Theron",
    "Hugh Jackman",
    "Daniel Radcliffe",
    "Rupert Grint",
    "Emma Watson",
    "Ralph Fiennes",
    "Morgan Freeman",
    "Will Smith",
    "Jada Pinkett Smith",
    "Chris Rock",
    "Dave Chappelle",
    "Trevor Noah",
    "Stephen Colbert",
    "Jimmy Fallon",
    "Jimmy Kimmel",
    "John Oliver",
    "Conan O’Brien",
    "Ellen DeGeneres",
    "Howard Stern",
    "Joe Rogan",
    "Greta Thunberg",
    "Malala Yousafzai",
    "Ruth Bader Ginsburg",
    "Michelle Obama",
    "Kamala Harris",
    "Alexandria Ocasio-Cortez",
    "Hillary Clinton",
    "Margaret Thatcher",
    "Angela Davis",
    "Condoleezza Rice",
    "Anne Frank",
    "Mother Teresa",
    "Florence Nightingale",
    "Clara Barton",
    "Jane Goodall",
    "Rosalind Franklin",
    "Katherine Johnson",
    "Grace Hopper",
    "Mae Jemison",
    "Chien-Shiung Wu",
    "Yuri Gagarin",
    "Neil Armstrong",
    "Buzz Aldrin",
    "Sally Ride",
    "Yoshua Bengio",
    "Geoffrey Hinton",
    "Yann LeCun",
    "Demis Hassabis",
    "Ilya Sutskever",
    "Sam Altman",
    "Dario Amodei",
    "Andrew Ng",
    "Fei-Fei Li",
    "Lex Fridman",
    "Linus Torvalds",
    "Guido van Rossum",
    "Brendan Eich",
    "James Gosling",
    "Bjarne Stroustrup",
    "Ken Thompson",
    "Dennis Ritchie",
    "Brian Kernighan",
    "Donald Knuth",
    "John Carmack",
    "Gabe Newell",
    "Shigeru Miyamoto",
    "Hideo Kojima",
    "Satoru Iwata",
    "Masahiro Sakurai",
    "Tetsuya Nomura",
    "Reggie Fils-Aimé",
    "Phil Spencer",
    "Todd Howard",
    "Cory Barlog",
    "Sheryl Sandberg",
    "Susan Wojcicki",
    "Marissa Mayer",
    "Meg Whitman",
    "Ginni Rometty",
    "Jensen Huang",
    "Lisa Su",
    "Andy Jassy",
    "Michael Dell",
    "Tim Berners-Lee",
    "Vint Cerf",
    "Peter Thiel",
    "Marc Andreessen",
    "Paul Graham",
    "Reid Hoffman",
    "Patrick Collison",
    "John Collison",
    "Brian Chesky",
    "Travis Kalanick",
    "Garrett Camp",
    "Drew Houston",
    "Arash Ferdowsi",
    "Evan Spiegel",
    "Bobby Murphy",
    "Kevin Systrom",
    "Mike Krieger",
    "Jack Dorsey",
    "Biz Stone",
    "Noam Chomsky",
    "Jordan Peterson",
    "Slavoj Žižek",
    "Yuval Noah Harari",
    "Steven Pinker",
    "Richard Dawkins",
    "Daniel Kahneman",
    "Amos Tversky",
    "Nassim Nicholas Taleb",
    "Eliezer Yudkowsky",
    "Immanuel Kant",
    "Friedrich Nietzsche",
    "Karl Marx",
    "Sigmund Freud",
    "Jean-Paul Sartre",
    "Simone de Beauvoir",
    "Michel Foucault",
    "Albert Camus",
    "Bertrand Russell",
    "David Hume",
    "John Locke",
    "Thomas Hobbes",
    "René Descartes",
    "Francis Bacon",
    "John Stuart Mill",
    "Confucius",
    "Laozi",
    "Sun Tzu",
    "Siddhartha Gautama",
    "Pablo Picasso",
    "Vincent van Gogh",
    "Claude Monet",
    "Salvador Dalí",
    "Michelangelo",
    "Raphael",
    "Rembrandt",
    "Johannes Vermeer",
    "Andy Warhol",
    "Frida Kahlo",
    "Diego Rivera",
    "Georgia O’Keeffe",
    "Jackson Pollock",
    "Banksy",
    "Takashi Murakami",
    "Hayao Miyazaki",
    "Isao Takahata",
    "Akira Kurosawa",
    "Yasujiro Ozu",
    "Bong Joon-ho",
    "Christopher Nolan",
    "Quentin Tarantino",
    "Steven Spielberg",
    "James Cameron",
    "Martin Scorsese",
    "Stanley Kubrick",
    "George Lucas",
    "Ridley Scott",
    "Peter Jackson",
    "Guillermo del Toro",
    "Greta Gerwig",
    "Denis Villeneuve",
    "Jordan Peele",
    "Ava DuVernay",
    "Taika Waititi",
    "John Williams",
    "Hans Zimmer",
    "Ennio Morricone",
    "Ramin Djawadi",
    "Joe Hisaishi",
    "Ludwig Göransson",
    "Alan Silvestri",
    "Danny Elfman",
    "Howard Shore",
    "Trent Reznor",
    "Atticus Ross",
    "Hildur Guðnadóttir",
    "Max Richter",
    "Yoko Shimomura",
    "Koji Kondo",
    "John Coltrane",
    "Miles Davis",
    "Louis Armstrong",
    "Duke Ellington",
    "Charlie Parker",
    "Ella Fitzgerald",
    "Billie Holiday",
    "Nina Simone",
    "Frank Ocean",
    "Kendrick Lamar",
];
